<?php
declare(strict_types=1);

function catalog_config(string $kind): array {
    return $kind==='careers' ? ['cap'=>'careers.edit','table'=>'vacancies','label'=>'Vacancy','fields'=>['title','location','type','team','summary','requirements','sort','published','closed']] : ['cap'=>'services.edit','table'=>'services','label'=>'Service','fields'=>['title','slug','note','body','icon','sort','featured']];
}
function catalog_index(string $kind): void { $c=catalog_config($kind);require_login();require_can($c['cap']);$order=$kind==='careers'?'closed_at IS NOT NULL, sort, title':'sort, title';admin_view('catalog-index',['title'=>ucfirst($kind),'kind'=>$kind,'config'=>$c,'rows'=>db_all("SELECT * FROM {$c['table']} ORDER BY {$order}")]); }
function catalog_form(string $kind,?int $id=null): void { $c=catalog_config($kind);require_login();require_can($c['cap']);$row=$id?db_one("SELECT * FROM {$c['table']} WHERE id=?",[$id]):null;if($id&&!$row){http_response_code(404);admin_view('error',['code'=>404,'title'=>$c['label'].' not found','message'=>'That record does not exist.']);return;}admin_view('catalog-form',['title'=>($id?'Edit ':'Add ').strtolower($c['label']),'kind'=>$kind,'config'=>$c,'row'=>$row]); }
function catalog_save(string $kind,?int $id=null): never { $c=catalog_config($kind);require_login();require_can($c['cap']);$title=(string)input('title','');if($title===''){flash('error','Title is required.');redirect(admin_url($kind.($id?'/'.$id:'/new')));}$u=current_user();if($kind==='careers'){$req=array_values(array_filter(array_map('trim',preg_split('/\r?\n/',(string)input('requirements',''))?:[])));$published=$id?db_value('SELECT published_at FROM vacancies WHERE id=?',[$id]):null;$data=['title'=>$title,'location'=>(string)input('location',''),'type'=>(string)input('type','Full time'),'team'=>input('team'),'summary'=>input('summary'),'requirements'=>json_encode($req),'sort'=>(int)input('sort','0'),'published_at'=>isset($_POST['published'])?($published?:now()):null,'closed_at'=>isset($_POST['closed'])?now():null,'updated_at'=>now(),'updated_by'=>$u['id']];}else{$slug=trim((string)input('slug',''));$slug=$slug!==''?$slug:strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$title)??'','-'));$data=['title'=>$title,'slug'=>$slug,'note'=>input('note'),'body'=>input('body'),'icon'=>(string)input('icon','check'),'sort'=>(int)input('sort','0'),'featured'=>isset($_POST['featured'])?1:0,'updated_at'=>now(),'updated_by'=>$u['id']];}if($id){db_update($c['table'],$id,$data);$action='updated';}else{$data['created_at']=now();$id=db_insert($c['table'],$data);$action='created';}log_activity($action,rtrim($kind,'s'),(string)$id,ucfirst($action).' '.$title);flash('success',$c['label'].' saved.');redirect(admin_url($kind.'/'.$id)); }
function careers_index():void{catalog_index('careers');} function careers_create():void{catalog_form('careers');} function careers_store():never{catalog_save('careers');} function careers_edit(string $id):void{catalog_form('careers',(int)$id);} function careers_update(string $id):never{catalog_save('careers',(int)$id);}
function services_index():void{catalog_index('services');} function services_create():void{catalog_form('services');} function services_store():never{catalog_save('services');} function services_edit(string $id):void{catalog_form('services',(int)$id);} function services_update(string $id):never{catalog_save('services',(int)$id);}
